<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerG1iq9sZ\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerG1iq9sZ/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerG1iq9sZ.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerG1iq9sZ\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerG1iq9sZ\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'G1iq9sZ',
    'container.build_id' => 'f288983a',
    'container.build_time' => 1610026688,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerG1iq9sZ');
